import './globals.css';
import Navbar from './components/NavBar/Navbar';
import { Roboto } from 'next/font/google';
import ContextProvider from './Context/ContextProvider';

const roboto = Roboto({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
});
export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<ContextProvider>
					<Navbar />

					{children}
				</ContextProvider>
			</body>
		</html>
	);
}
